apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cafestatic-rollout
  labels:
    app: cafestatic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafestatic
  template:
    metadata:
      labels:
        app: cafestatic
    spec:
      containers:
      - name: cafestatic
        image: sreedocker123/cafewebimage:final
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 50
      - pause: {duration: 10s}
      - setWeight: 80
      - pause: {duration: 10s}
