apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: php-mysql-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cafestatic
  template:
    metadata:
      labels:
        app: cafestatic
    spec:
      containers:
      - name: php-container
        image: sreedocker123/cafewebimage:final
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 40
      - pause: {duration: 10s}
      - setWeight: 60
      - pause: {duration: 10s}
      - setWeight: 80
      - pause: {duration: 10s}
